version: 2

jobs:
  build:
    working_directory: ~/gdso-avito
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: env and run tests
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            pip install --upgrade pip
            pip install --quiet -r requirements.txt
            python setup.py test
          no_output_timeout: 20m